#!/bin/sh
# shellcheck shell=sh

MENU="${MENU:-bemenu}"

MENU_FONT="${MENU_FONT:-JetbrainsMono Medium}"
MENU_FONT_SIZE="${MENU_FONT_SIZE:-12}"
MENU_COL_WHITE="${MENU_COL_WHITE:-#ebdbb2}" # White
MENU_COL_SB="${MENU_COL_SB:-#7fbbb3}"       # Selected background
MENU_COL_SF="${MENU_COL_SF:-#1e2326}"       # Selected foreground
MENU_COL_NB="${MENU_COL_NB:-#1e2326}"       # Normal background
MENU_COL_NF="${MENU_COL_NF:-#374145}"       # Normal foreground

_help() {
  printf "Usage: menu [run/dmenu/pass] [prompt...]\nDefault backend: %s\n" "$MENU"
}

_args="$*"

case "$_args" in
*"-h"*)
  _help
  exit 0
  ;;
"")
  _help
  exit 0
  ;;
esac

MODE="$1"
PROMPT="${_args#*"$MODE" }"

if [ "$MODE" = "$PROMPT" ]; then
  PROMPT=
fi

case "$MODE" in
run) ;;
dmenu) ;;
pass) ;;
*)
  echo "Unknown mode '$MODE'" >>/dev/stderr
  exit 1
  ;;
esac

_bemenu() {
  if [ "$PROMPT" ]; then
    prompt_flag="-p"
  fi

  case "$MODE" in
  run) run="-run" ;;
  pass) pass="-x indicator" ;;
  esac

  # shellcheck disable=SC2086
  bemenu"$run" \
    $prompt_flag $PROMPT \
    $pass \
    --no-exec -i -c \
    -l 10 -W 0.4 -B 2 -H 30 --cw 1 \
    --tb "$MENU_COL_SB" --tf "$MENU_COL_SF" \
    --fb "$MENU_COL_NB" --ff "$MENU_COL_NF" \
    --cb "$MENU_COL_NB" --cf "$MENU_COL_WHite" \
    --nb "$MENU_COL_NB" --nf "$MENU_COL_NF" \
    --hb "$MENU_COL_SB" --hf "$MENU_COL_SF" \
    --ab "$MENU_COL_NB" --af "$MENU_COL_NF" \
    --bdr "$MENU_COL_SB" \
    --fn "$MENU_FONT $MENU_FONT_SIZE"
}

_dmenu() {
  if [ "$PROMPT" ]; then
    prompt_flag="-p"
  fi

  case "$MODE" in
  run) run="_run" ;;
  # pass) pass="-P" ;; # Needs a patch
  esac

  # shellcheck disable=SC2086
  dmenu"$run" \
    $prompt_flag $PROMPT \
    $pass \
    -i \
    -l 10 \
    -nb "$MENU_COL_NB" -nf "$MENU_COL_NF" \
    -sb "$MENU_COL_SB" -sf "$MENU_COL_SF" \
    -fn "$MENU_FONT:size=$MENU_FONT_SIZE"
}

if command -v _"$MENU" >/dev/null 2>&1; then
  _"$MENU"
else
  echo "Unable to find menu backend for '$MENU'" >>/dev/stderr
  exit 1
fi
